### ISSUE TITLE
Not displaying a footer

### ISSUE THREAD

**Issue by romant** [MeteorStuff/meteor-materialize-modal#11]
What's the best way to hide, or rather not render the `modal-footer` div at all?

**Comment by jitteryjuice** [comment]
I am also wondering this, i have my own modal-footer in my template that is being rendered yet cannot remove the built in ones (either with the form template, or just 'display')

**Comment by jitteryjuice** [comment]
@romant the best way ive found (from the docs), is to use ' closeLabel: null, ' in the MaterializeModal.display({}) inside the template you're using.. it still has the space at the bottom but the buttons arent there anymore

**Comment by pfafman** [comment]
You might want to use [modalize](https://github.com/msolters/modalize) instead.  @msolters forked this project and created modalize for just this type of issue.  It is a little more complicated to use but does what you are looking for.

My goal for this project was to just make simple materializecss modals that you can use across your project.  For complicated ones it still in my opinion makes more sense to write your own template from scratch.
