### ISSUE TITLE
OutDuration no effect

### ISSUE THREAD

**Issue by zhaoyao91** [MeteorStuff/meteor-materialize-modal#16]
by specifying `outDuration`, it only takes effect when click the background. however, when click close button or by invoke close function, it doesn't take effect.

**Comment by pfafman** [comment]
This is a pass through option to materializecss.  Open a ticket with them unless you can verify that it is not an issue with them and is something to do with the pass through.

**Comment by zhaoyao91** [comment]
I have test that, the result for materializecss is:
1. if you set `out_duration` on `openModa()l`, it will affect `click background` and `click close button`
2. if you set `out_duration` on `closeModal()`, it will affect `closeModal()`

the result for your modal is:
1. if you set `outDuration` on `display()`, it will affect `click background`
2. if you set `outDuration` on `close()`, it will affect nothing

**Comment by pfafman** [comment]
Should be fixed in 1.0.6
There is a demo of it working on the [demo site](http://materializemodal.meteor.com/#options).

**Comment by zhaoyao91** [comment]
thanks, it now works slightly different with materializecss but fine.
