### ISSUE TITLE
Modals Block Toasts

### ISSUE THREAD

**Issue by msolters** [MeteorStuff/meteor-materialize-modal#2]
Toasts should have the maximum z-index.  Materialize defines them at `z-index: 1001`.  We should look into either sending a PR to Materialize redefining them (perhaps 1005), or to move the modal z-index to N < 1001 and the lean-overlay to N-1.

**Comment by pfafman** [comment]
I don't think the Materialize UI is meant to have a toast while a modal is open.  User feedback should probably be in the modal, which this package does not really take care of.
