### ISSUE TITLE
Dependency on Materialize should be explicit

### ISSUE THREAD

**Issue by AlexeyMK** [MeteorStuff/meteor-materialize-modal#21]
This package neither includes Materialize's code for openModal/closeModal, nor relies on a package like    https://github.com/Dogfalo/materialize to provide the functionality.  This results in an implicit dependency, causing bugs which are particularly confusing to catch.

**Proposed Solution** Either explicitly depend on `materialize:materialize` in `package.js` or directly copy `https://github.com/Dogfalo/materialize/blob/master/js/leanModal.js` into the project.

Edit: I realize the Install guidelines should have warned me about this

> You are required to get Materialize on your own, either from a package or inserting it manually into your meteor app. This allows you to either use a CSS or SASS version for more customization.

Still, I think it would be reasonable to have a line of code that checks if Materialize has been imported, and if not, import the bare minimum JS.

**Comment by pfafman** [comment]
I could see throwing an error if Materialize is not present but importing it if not would lead to a mess and might not even be possible or desired within meteor.

The assumption is that if you are using or want to use this package your app already is using Materializecss.

**Comment by AlexeyMK** [comment]
@pfafman the issue you're facing is, if I look for Modals on atmosphere you're the top solution. I would prefer to use modals without Materialize, but I'm not seeing a package for it.

**Comment by pfafman** [comment]
Then write one.

**Comment by AlexeyMK** [comment]
¯_(ツ)_/¯ fair enough, I hear you.

FWIW, Throwing an explicit error when you can't detect `$(body).openModal` would have saved me several hours of time.
