### ISSUE TITLE
removing title, adds modal's action div + buttons

### ISSUE THREAD

**Issue by romant** [MeteorStuff/meteor-materialize-modal#23]
```
MaterializeModal.form({
      bodyTemplate: "myTemplate"
    });
```

renders with an `Edit Record` title.
### unexpected behaviour

Removing title by virtue of `title=""` in the definition; ends up adding `Save` and `Cancel` buttons in the modal action; resulting in having to have the whole definition as follows:

```
MaterializeModal.form({
      title: "",
      closeLabel: "",
      submitLabel: "",
      bodyTemplate: "myTemplate"
    });
```

**Comment by pfafman** [comment]
For now that is the expected behavior.

If you do not specify ['title', 'submittable']  you get the defaults
