### ISSUE TITLE
Please make documentation available

### ISSUE THREAD

**Issue by ahmedtabrez** [MeteorStuff/meteor-materialize-modal#31]
After the ***.meteor.com** sites have been disabled for free users at meteor.com, **http://materializemodal.meteor.com/** has been down. Has the demo site been moved to some other location ???

**Comment by pfafman** [comment]
No.  Have not found a suitable free place to host it.  If you know of one let me know.

**Comment by ahmedtabrez** [comment]
@pfafman, I too tried hard but unfortunately couldn't find any free host. Most of the hosts are paid, some offer free but for a limited time with Amazon AWS being the best of them as it offers one full free year. 

Anyhow, I would like to suggest that you could create another github repo and push the demo site there. your package is absolutely great and doesn't deserve to sit there just like that without telling people how to use it.
