### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gernotthrive** [MeteorStuff/meteor-materialize-modal#5]
on your example page and I have the same issue locally

Uncaught RangeError: Maximum call stack size exceededp.$modal.openModal.ready @ 7635daf553415fc972778047a92194541e7f9f7d.js?meteor_js_resource=true:102p.$modal.openModal.ready @ 7635daf553415fc972778047a92194541e7f9f7d.js?meteor_js_resource=true:102p.$modal.openModal.ready @ 7635daf553415fc972778047a92194541e7f9f7d.js?meteor_js_resource=true:102p.$modal.openModal.ready @ 7635daf553415fc972778047a92194541e7f9f7d.js?meteor_js_resource=true:102p.$modal.openModal.ready @ 7635daf553415fc972778047a92194541e7f9f7d.js?meteor_js_resource=true:102p.$modal.openModal.ready @ 7635daf553415fc972778047a92194541e7f9f7d.js?meteor_js_resource=true:102p.$modal.openModal.ready @ 7635daf553415fc972778047a92194541e7f9f7d.js?meteor_js_resource=true:102p.$modal.openModal.ready @ 7635daf553415fc972778047a92194541e7f9f7d.js?meteor_js_resource=true:102p.$modal.openModal.ready @ 7635daf553415fc972778047a92194541e7f9f7d.js?meteor_js_resource=true:102p.$modal.openModal.ready @ 7635daf553415fc972778047a92194541e7f9f7d.js?meteor_js_resource=true:102

**Comment by msolters** [comment]
What browser/OS?  Is this in response to a specific call, or on page load?

**Comment by gernotthrive** [comment]
on any button i click on the page to show a modal.
Ubuntu 15.04 - chrome Version 46.0.2490.71 (64-bit)

**Comment by msolters** [comment]
Yeah I can confirm that.

Does this occur with the package in general (i.e. it's affecting any app it's in)?  Or only in clones of the demo site?

**Comment by gernotthrive** [comment]
I just installed your library via meteor and loaded a modal from a template i created, had the JS error occur and thought it is on my side so I checked your page. So not only demo site, I think it's a more general

**Comment by msolters** [comment]
Ok great.  Last I worked on this there was no error.

So, first bug I see is here:  https://github.com/MeteorStuff/meteor-materialize-modal/blob/master/lib/modal.coffee#L64

Other than that, looks like @pfafman pushed a new version just yesterday (?)  Not sure what those changes were for.  I will try to test this more later this evening.

**Comment by msolters** [comment]
Oh no I know exactly what's happening!  `ready()` is calling `@ready()`!!  Whaaaaat

**Comment by gernotthrive** [comment]
thanks very much. btw awesome work on this .. tried some other libraries already but this one seems like the best option :)

**Comment by pfafman** [comment]
My mistake.  It was the wrong context for returning the ready function that is in the normal materialize modem.

**Comment by msolters** [comment]
Don't thank me, thank @pfafman!

FWIW I also maintain a more Meteoric version over at http://modalize.meteor.com.  It has more control but requires more work.  Just FYI :)

@pfafman I added the fix (untested--I only removed `@ready()`, sorry if that breaks something you were working on?  I didn't see any other method called `ready` ) -- do you want to handle publishing a new version?

**Comment by pfafman** [comment]
I already did.  Not sure why anyone would want it but was trying to return all the options that are available in the materialize modem.

**Comment by msolters** [comment]
Awesome!  :+1: :rocket: :100:
