### ISSUE TITLE
Fullscreen Modals Blocked by Nav

### ISSUE THREAD

**Issue by msolters** [MeteorStuff/meteor-materialize-modal#6]
It seems that modals are being rendered at an effective z-index less than that of what Materialize uses for (fixed) navbars.  As a result, fullscreen modals will have their content hidden underneath the navbar!

We should ensure that modals always appear _over_ the navbar, especially when fullscreen.

**Comment by pfafman** [comment]
This should be taken up with [materializecss](http://materializecss.com]) or the end use should just fix in their CSS.  Overwriting here would add to CSS complexity which in my opinion should be with in [materializecss](http://materializecss.com]) or the enduser's app.
